import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/footer";
import HeaderFixo from "@/components/common/headerFixo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <HeaderFixo />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
